version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo Build Starting on `date` 
      - chmod +x ./gradlew
      - ./gradlew build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./build/libs/*.jar) 
      - pwd 

artifacts:
  files:
    - build/libs/*.jar 
    - appspec.yml
    - script/start.sh
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    
    