version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo Build Starting on `date` 
#     - cp ./src/main/resources/application.yml ./src/main/resources/application-${profile}.yml
#      - chmod +x ./gradlew
#      - ./gradlew build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./build/libs/*.jar) 
      - pwd 
#     - mkdir -p deploy
#     - cp ./build/libs/*.jar ./deploy
#     - zip -r ./kokonut_deploy.zip ./deploy
#     - aws s3 cp --region ap-northeast-2 ./kokonut_deploy.zip s3://kokonut-server-update-20230213/upload/build_projectfile/ 

artifacts:
  files:
    - build/libs/*.jar 
    - appspec.yml
    - script/start.sh
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    
    